# MODEL CONFIG
MODEL_NAME = "vit_small"
PATCH_SIZE = 16
PRETRAINED = True

# TRAIN CONFIG
EPOCHS = 1000
WARMUP_EPOCH = 10
BATCH_SIZE = 64
LEARNING_RATE = 1e-5
OPTIMIZER = 'adamw'
ADAMW_BETA1 = 0.9
ADAMW_BETA2 = 0.999

# DATA CONFIG
GLOBAL_IMG_SIZE = 224
LOCAL_IMG_SIZE = 112
NUM_LOCAL = 1
GLOBAL_CROP_RATIO = (0.8, 1.)
LOCAL_CROP_RATIO = (0.7, 0.8)




